#
#
# Copyright 2016 The Symphony Software Foundation
#
# Licensed to The Symphony Software Foundation (SSF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# Required by Sonar plugin
dist: trusty
sudo: required

language: java

script: 
  - "if [[ $TRAVIS_BRANCH =~ master && \"$TRAVIS_PULL_REQUEST\" = \"false\" ]]; then mvn clean deploy -Pversioneye --settings settings.xml ; else mvn clean install ; fi"
  - sonar-scanner

jdk:
  - oraclejdk8

env:
  global:
   # Need to "gem install travis" first
   # To enable Sonar, Generate a secure using command "travis encrypt SONAR_LOGIN=blah"
   # Generated using command "travis encrypt VERSIONEYE_API_KEY=blah"
   - secure: "PeKOd8DWCT8d7zLQKyB86gt2qz0qpiSAujUa2hUyNFajSOv6iZZ9Zn0QUAb6ZqBavCC6ytIdxSFxWYLlTo48joJ++2qimfvX2Xwz/vO4n1qA1k/gwl3BBrMN9FX0wnE2WKt1fEOQgMDaPnoYqezPSGPbKB/f4ph4siW6ory4evFNNd9yWm8Y39v6C7cPxQXiGP8NdhfNfH5Fqdlz3pEa+tv128SyCHaGdL3qt0ghfMVxQ8lMSMihKi7PM0nn6s5R6/YGOUoCSSFT52l0/Zy14PW91Rn2AF3CN24ywll9OES2OefgDIzWCJ1v5cHWBbW4JQJkb4LVAnf/EoLYKe3MFX43T7JVa3a6uLjn+8/VcsDYVy0Lv6L0B/F1gf3dTcUipYNQXhWqfRy8px7oeIssq6O/cPm/TjTL7wNbrqyymnLjdn2NDvaaG5BMIhirekBltRceX3NmQCGBOLHDDum7N79B/rhJk97BBCstzveOYmIGtTDwnS0ub81bxPKz6aDjFELHgEli1Wdjro41Hd3NuFLjuRwuaCMHylWyzMejNhb/UcnoP/Mq9KiYAgDOUS/l/YyIvBpUI7MBAIAiEhDRiqKJexCRusAb9UBeh73iESQF3hkp0RgLb9J/PAmUgHqhTOgUDrm3ETiSDrW/npixsGTIWuvVrPYtZgUpbmXA5jQ="

cache:
  directories:
    - '$HOME/.sonar/cache'

addons:
  sonarqube:
    organization: "symphonyoss"